core/routes/web.php
<?php
Route::group(['prefix'=>'admin', 'middleware'=>'guest:admin'], function (){
    Route::get('/', 'Web\AdminController@showLoginForm')->name('admin.login');
    Route::post('/', 'Web\AdminController@login');
});

Route::group(['prefix'=>'admin', 'middleware'=>'auth:admin'], function (){
    Route::get('home', 'Web\AdminController@homeMethod')->name('admin.home');

    Route::get('profile', 'Web\AdminController@showProfileForm')->name('admin.profile');
    Route::put('profile', 'Web\AdminController@submitProfileForm');
    Route::get('password', 'Web\AdminController@showPasswordForm')->name('admin.password');
    Route::post('password', 'Web\AdminController@submitPasswordForm');

    Route::get('settings/general', 'Web\AdminController@showGeneralSettingsForm')->name('admin.settings_general');
    Route::put('settings/general', 'Web\AdminController@submitGeneralSettingsForm');

    Route::get('settings/media', 'Web\AdminController@showMediaSettingsForm')->name('admin.settings_media');
    Route::put('settings/media', 'Web\AdminController@submitMediaSettingsForm');

    Route::get('settings/headlines', 'Web\AdminController@showHeadlinesSettingForm')->name('admin.settings_headlines');
    Route::put('settings/headlines', 'Web\AdminController@submitHeadlinesSettingForm');

    Route::get('settings/headlines/sub', 'Web\AdminController@showSubHeadlinesSettingForm')->name('admin.settings_sub_headlines');
    Route::put('settings/headlines/sub', 'Web\AdminController@submitSubHeadlinesSettingForm');

    Route::get('settings/categories/menu', 'Web\AdminController@showMenuCategoriesForm')->name('admin.settings_menu_categories');
    Route::put('settings/categories/menu', 'Web\AdminController@submitMenuCategoriesForm');

    Route::get('settings/categories/front', 'Web\AdminController@showFrontCategoriesForm')->name('admin.settings_index_categories');
    Route::put('settings/categories/front', 'Web\AdminController@submitFrontCategoriesForm');

    Route::get('settings/categories/footer', 'Web\AdminController@showFooterCategoriesForm')->name('admin.settings_footer_categories');
    Route::put('settings/categories/footer', 'Web\AdminController@submitFooterCategoriesForm');

    Route::get('videos/create', 'Web\AdminController@showCreateVideoForm')->name('admin.videos.create');
    Route::post('videos', 'Web\AdminController@submitCreateVideoForm')->name('admin.videos.store');
    Route::get('videos', 'Web\AdminController@showAllVideos')->name('admin.videos.index');
    Route::get('videos/{video}/edit', 'Web\AdminController@showVideoEditForm')->name('admin.videos.edit');
    Route::put('videos/{video}', 'Web\AdminController@submitVideoEditForm')->name('admin.videos.update');
    Route::delete('videos/{video}', 'Web\AdminController@videoDeleteMethod')->name('admin.videos.destroy');

    Route::get('images/create', 'Web\AdminController@showCreateImageForm')->name('admin.images.create');
    Route::post('images', 'Web\AdminController@submitCreateImageForm')->name('admin.images.store');
    Route::get('images', 'Web\AdminController@showAllImages')->name('admin.images.index');
    Route::get('images/{image}/edit', 'Web\AdminController@showImageEditForm')->name('admin.images.edit');
    Route::put('images/{image}', 'Web\AdminController@submitImageEditForm')->name('admin.images.update');
    Route::delete('images/{image}', 'Web\AdminController@imageDeleteMethod')->name('admin.images.destroy');

    Route::get('categories/create', 'Web\AdminController@showCreateCategoryForm')->name('admin.categories.create');
    Route::post('categories', 'Web\AdminController@submitCreateCategoryForm')->name('admin.categories.store');
    Route::get('categories', 'Web\AdminController@showAllCategories')->name('admin.categories.index');
    Route::get('categories/{category}/edit', 'AdminController@showCategoryEditForm')->name('admin.categories.edit');
    Route::put('categories/{category}', 'AdminController@submitCategoryEditForm')->name('admin.categories.update');
    Route::delete('categories/{category}', 'AdminController@categoryDeleteMethod')->name('admin.categories.destroy');

    Route::get('editors/create', 'AdminController@showCreateEditorForm')->name('admin.editors.create');
    Route::post('editors', 'AdminController@submitCreateEditorForm')->name('admin.editors.store');
    Route::get('editors', 'AdminController@showAllEditors')->name('admin.editors.index');
    Route::get('editor/{editor}/edit', 'AdminController@showEditorEditForm')->name('admin.editors.edit');
    Route::put('editors/{editor}', 'AdminController@submitEditorEditForm')->name('admin.editors.update');
    Route::delete('editors/{editor}', 'AdminController@editorDeleteMethod')->name('admin.editors.destroy');

    Route::get('reporters/create', 'AdminController@showCreateReporterForm')->name('admin.reporters.create');
    Route::post('reporters', 'AdminController@submitCreateReporterForm')->name('admin.reporters.store');
    Route::get('reporters', 'AdminController@showAllReporters')->name('admin.reporters.index');
    Route::get('reporters/{reporter}/edit', 'AdminController@showReporterEditForm')->name('admin.reporters.edit');
    Route::put('reporters/{reporter}', 'AdminController@submitReporterEditForm')->name('admin.reporters.update');
    Route::delete('reporters/{reporter}', 'AdminController@reporterDeleteMethod')->name('admin.reporters.destroy');

    Route::get('news/create', 'AdminController@showCreateNewsForm')->name('admin.news.create');
    Route::post('news', 'AdminController@submitCreateNewsForm')->name('admin.news.store');
    Route::get('news', 'AdminController@showAllNews')->name('admin.news.index');
    Route::get('news/{news}/edit', 'AdminController@showNewsEditForm')->name('admin.news.edit');
    Route::put('news/{news}', 'AdminController@submitNewsEditForm')->name('admin.news.update');
    Route::delete('news/{news}', 'AdminController@newsDeleteMethod')->name('admin.news.destroy');

    Route::get('logout', 'Web\AdminController@logout')->name('admin.logout');
});

Route::group(['prefix'=>'editor', 'middleware'=>'guest:editor'], function (){
    Route::get('/', 'Web\EditorController@showLoginForm')->name('editor.login');
    Route::post('/', 'Web\EditorController@login');
});

Route::group(['prefix'=>'editor', 'middleware'=>'auth:editor'], function(){
    Route::get('home', 'Web\EditorController@homeMethod')->name('editor.home');

    Route::get('update/profile', 'Web\EditorController@showProfileForm')->name('editor.profile');
    Route::put('update/profile', 'Web\EditorController@submitProfileForm');
    Route::get('update/password', 'Web\EditorController@showPasswordForm')->name('editor.password');
    Route::put('update/password', 'Web\EditorController@submitPasswordForm');

    Route::get('news', 'Web\EditorController@showAllNews')->name('editor.news.index');
    Route::get('news/{news}/edit', 'EditorController@showNewsEditForm')->name('editor.news.edit');
    Route::put('news/{news}', 'EditorController@submitNewsEditForm')->name('editor.news.update');
    // Route::delete('news/delete/{newsId}', 'EditorController@newsDeleteMethod')->name('editor.delete.news');

    Route::get('images', 'EditorController@showAllImages')->name('editor.images.index');
    Route::get('images/{image}/edit', 'EditorController@showImageEditForm')->name('editor.images.edit');
    Route::put('images/{image}', 'EditorController@submitImageEditForm')->name('editor.images.update');

    Route::get('videos', 'EditorController@showAllVideos')->name('editor.videos.index');
    Route::get('videos/{video}/edit', 'EditorController@showVideoEditForm')->name('editor.videos.edit');
    Route::put('videos/{video}', 'EditorController@submitVideoEditForm')->name('editor.videos.update');

    Route::get('logout', 'EditorController@logout')->name('editor.logout');
});

Route::group(['prefix'=>'reporter', 'middleware'=>'guest:reporter'], function (){
    Route::get('/', 'ReporterController@showLoginForm')->name('reporter.login');
    Route::post('/', 'ReporterController@login')->name('reporter');
});

Route::group(['prefix'=>'reporter', 'middleware'=>'auth:reporter'], function(){
    Route::get('home', 'ReporterController@homeMethod')->name('reporter.home');

    Route::get('update/profile', 'ReporterController@showProfileForm')->name('reporter.profile');
    Route::put('update/profile', 'ReporterController@submitProfileForm');
    Route::get('update/password', 'ReporterController@showPasswordForm')->name('reporter.password');
    Route::put('update/password', 'ReporterController@submitPasswordForm');

    Route::get('news/create', 'ReporterController@showCreateNewsForm')->name('reporter.news.index');
    Route::post('news', 'ReporterController@submitCreateNewsForm')->name('reporter.news.store');
    Route::get('news', 'ReporterController@showAllNews')->name('reporter.news.index');
    Route::get('news/{news}/edit', 'ReporterController@showNewsEditForm')->name('reporter.news.edit');
    Route::put('news/{news}', 'ReporterController@submitNewsEditForm')->name('reporter.news.update');


    Route::get('images/create', 'ReporterController@showCreateImageForm')->name('reporter.images.create');
    Route::post('images', 'ReporterController@submitCreateImageForm')->name('reporter.images.store');
    Route::get('images', 'ReporterController@showAllImages')->name('reporter.images.index');
    Route::get('images/{image}/edit', 'ReporterController@showImageEditForm')->name('reporter.images.edit');
    Route::put('images/{image}', 'ReporterController@submitImageEditForm')->name('reporter.images.update');

    Route::get('videos/create', 'ReporterController@showCreateVideoForm')->name('reporter.videos.create');
    Route::post('videos', 'ReporterController@submitCreateVideoForm')->name('reporter.videos.store');
    Route::get('videos', 'ReporterController@showAllVideos')->name('reporter.videos.index');

core/app/Models/Category.php
<?php

namespace App\Models;

use App\Post;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function childNews(){
        return $this->hasMany('App\News');
    }

    public function getNameParentAttribute(){
        if ($this->parent == 0)
            return 'none';
        else{
            $parent = Category::findOrFail($this->parent);
            return $parent->name;
        }
    }
}

core/app/Models/Editor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Editor extends Authenticatable
{
    use Notifiable;
    protected $guarded = ['id'];
//    public function category()
//    {
//        return $this->hasMany('App\Category');
//    }
    public function setEditorCategoriesAttribute($categories = array())
    {
        $this->attributes['categories_id'] = json_encode($categories);
    }

    public function getEditorCategoriesAttribute()
    {
        $caregoryIds = json_decode($this->categories_id);
        return Category::whereIn('id', $caregoryIds)->get(['id','name']);
    }
}

core/resources/views/admin/all_editors.blade.php
@extends('admin.layout.app')
@section('contents')

        <h2 class="mb-4"> Editor List </h2>
        <div class="card mb-4">
            <div class="card-body">
                <table class="table table-hover text-center" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Full Name</th>
                        <th>Username </th>
                        <th>Email</th>
                        <th>Categories</th>
                        <th>Phone</th>
                        <th class="actions">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($editors as $editor)
                        <tr>
                            <td>{{$editor->firstname}} {{$editor->lastname}}</td>
                            <td>{{ $editor->username }}</td>
                            <td>{{ $editor->email }}</td>
                            <td>
                            @foreach($editor->editor_categories as $category)
                                {{ $category->name }},
                            @endforeach
                                {{--{{ var_dump($editor->editor_categories)}}--}}
                            {{--{{ $editor->editor_categories}}--}}
                            </td>
                            <td>{{ $editor->phone }}</td>
                            <td>
                                <a href="{{ route('admin.edit_editor', $editor->id) }}" class="btn btn-icon btn-pill btn-success" data-toggle="tooltip" title="Edit">
                                    <i class="fa fa-fw fa-edit"></i>
                                </a>

                                <a data-toggle="modal" data-target="#myModal{{ $editor->id }}" class="btn btn-icon btn-pill btn-danger" data-toggle="tooltip" title="Delete">
                                    <i class="fa fa-fw fa-trash"></i>
                                </a>
                            </td>
                        </tr>

                        <!-- Modal -->
                        <div class="modal fade" id="myModal{{ $editor->id }}" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Confirmation</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>

                                    <form action="{{ route('admin.delete_editor', $editor->id) }}" method="POST">
                                        @method('delete')
                                        @csrf
                                        <div class="modal-body">
                                            <p>Are You Sure ??</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-success">Yes</button>
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="pagination text-right">
                {{ $editors->onEachSide(5)->links() }}
            </div>
        </div>
@stop

core/resources/views/admin/all_images.blade.php
@extends('admin.layout.app')
@section('contents')

    <h2 class="mb-4"> Image's List </h2>
    <div class="card mb-4">
        <div class="card-body">
            <table class="table table-hover text-center" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>Image Id</th>
                    <th>Image Title </th>
                    <th>description</th>
                    <th>Status</th>
                    <th class="actions">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($allImages as $image)
                    <tr>
                        <td>{{ $image->id }}</td>
                        <td>{{ $image->title }}</td>
                        <td>{{ str_limit($image->description, 60) }}</td>
                        
                        <td>
                            <input type="checkbox" @if($image->status==1) checked @endif disabled>Published
                            <input type="checkbox" @if($image->status==0) checked @endif disabled>Unpublished
                        </td>
                        <td>
                            <a href="{{ route('admin.edit_image', [$image->id]) }}" class="btn btn-icon btn-pill btn-success" data-toggle="tooltip" title="Edit">
                                <i class="fa fa-fw fa-edit"></i>
                            </a>

                            <a data-toggle="modal" data-target="#myModal{{ $image->id }}" class="btn btn-icon btn-pill btn-danger" data-toggle="tooltip" title="Delete">
                                <i class="fa fa-fw fa-trash"></i>
                            </a>
                            
                        </td>
                    </tr>

                    <div class="modal fade" id="myModal{{ $image->id }}" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Confirmation</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <form action="{{ route('admin.delete_image', $image->id) }}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <div class="modal-body">
                                        <p>Are You Sure ??</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-success">Yes</button>
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                @endforeach
                </tbody>
            </table>
        </div>
        <div class="pagination text-right">
        {{ $allImages->onEachSide(5)->links() }}
        </div>
    </div>
@stop

core/resources/views/admin/all_reporters.blade.php
@extends('admin.layout.app')
@section('contents')
        <h2 class="mb-4"> Employee List </h2>
        <div class="card mb-4">
            <div class="card-body">
                <table class="table table-hover text-center" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Full Name</th>
                        <th>Username </th>
                        <th>Email</th>
                        <th>Categories</th>
                        <th>Phone</th>
                        <th class="actions">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($reporters as $reporter)
                        <tr>
                            <td>{{$reporter->firstname}} {{$reporter->lastname}}</td>
                            <td>{{ $reporter->username }}</td>
                            <td>{{ $reporter->email }}</td>
                            <td> All Categoryies </td>
                            <td>{{ $reporter->phone }}</td>
                            <td>
                                <a href="{{ route('admin.edit_reporter',  $reporter->id) }}" class="btn btn-icon btn-pill btn-success" data-toggle="tooltip" title="Edit">
                                    <i class="fa fa-fw fa-edit"></i>
                                </a>

                                <a data-toggle="modal" data-target="#myModal{{ $reporter->id }}" class="btn btn-icon btn-pill btn-danger" data-toggle="tooltip" title="Delete">
                                    <i class="fa fa-fw fa-trash"></i>
                                </a>
                            </td>
                        </tr>

                        <!-- Modal -->
                        <div class="modal fade" id="myModal{{ $reporter->id }}" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Confirmation</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <form action="{{ route('admin.delete_reporter', $reporter->id) }}" method="POST">
                                        @method('delete')
                                        @csrf
                                        <div class="modal-body">
                                            <p>Are You Sure ??</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-success">Yes</button>
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="pagination text-right">
                {{ $reporters->onEachSide(5)->links() }}
            </div>
        </div>
@stop

core/resources/views/admin/all_videos.blade.php
@extends('admin.layout.app')
@section('contents')

        <h2 class="mb-4"> Video List </h2>
        <div class="card mb-4">
            <div class="card-body">
                <table class="table table-hover text-center" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Video Id</th>
                        <th>Video Title </th>
                        <th>Preview</th>
                        <th>Address</th>
                        <th>Status</th>
                        <th class="actions">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($allVideos as $video)
                        <tr>
                            <td>{{$video->id}}</td>
                            <td>{{ $video->title }}</td>
                            <td>
                                <img src="{{ asset('assets/front/images/video/'.$video->preview) }}" width="120" alt="No Image">
                            </td>
                            <td>{{ $video->videoaddress }}</td>
                            <td>
                                <input type="checkbox" @if($video->status==1) checked @endif disabled>Published
                                <input type="checkbox" @if($video->status==0) checked @endif disabled>Unpublished
                            </td>
                            <td>
                                <a href="{{ route('admin.edit_video', [$video->id]) }}" class="btn btn-icon btn-pill btn-success" data-toggle="tooltip" title="Edit">
                                    <i class="fa fa-fw fa-edit"></i>
                                </a>

                                <a data-toggle="modal" data-target="#myModal{{ $video->id }}" class="btn btn-icon btn-pill btn-danger" data-toggle="tooltip" title="Delete">
                                    <i class="fa fa-fw fa-trash"></i>
                                </a>
                            </td>
                        </tr>

                        <!-- Modal -->
                        <div class="modal fade" id="myModal{{ $video->id }}" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Confirmation</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <form action="{{ route('admin.delete_video', $video->id) }}" method="POST">
                                        @method('delete')
                                        @csrf
                                        <div class="modal-body">
                                            <p>Are You Sure ??</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-success">Yes</button>
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="pagination text-right">
            {{ $allVideos->onEachSide(5)->links() }}
            </div>
        </div>
@stop

core/resources/views/admin/create_category.blade.php
@extends('admin.layout.app')
@section('contents')
<div class="content p-4">
    <h2 class="mb-4"> Create Category </h2>
    <div class="card mb-4">
        <div class="card-body">
            <form method="POST" action = "{{ route('admin.created_category_submit') }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Category / Sub Category Name:</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control form-control-lg" placeholder="Category / Sub Category Name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Choose URL:</label>
                    <div class="col-sm-10">
                        <input type="text" name="url" class="form-control form-control-lg" placeholder="Browsing URL" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputCategory" class="col-sm-2 col-form-label">Choose Parent Name:</label>
                    <div class="col-sm-10">
                        <select class="form-control form-control-lg" name="parent" required>
                            <option selected value="0"> -- select a parent name -- </option>
                            @foreach($allCategories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-block btn-lg btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

core/resources/views/admin/index_categories.blade.php
@extends('admin.layout.app')
@section('contents')
    <div class="content p-4">
        <h2 class="mb-4"> Front Page Categories </h2>
        <div class="card mb-4">

            <div class="card-body text-center">
                <div class="row">
                    <div class="col-sm-3">
                        <h5 class="text-capitalize">Preference No</h5>
                    </div>
                    <div class="col-sm-3">
                        <h5 class="text-capitalize">Category Id</h5>
                    </div>
                    <div class="col-sm-3">
                        <h5 class="text-capitalize">Category Name</h5>
                    </div>
                    <div class="col-sm-3">
                        <h5 class="text-capitalize">Category Parent</h5>
                    </div>
                </div>

                <form method="post" action="{{route('admin.settings_index_categories_submit')}}">
                    @csrf
                    @method('put')
                    @for($i=0;$i<count($prioritizedCategoryDetails);$i++)
                    <div class="row">
                        <div class="col-sm-3">
                            <button type="button" class="btn btn-block btn-warning btn-arrow-right">Number {{$i+1}} </button>
                        </div>
                        <div class="col-sm-3">
                            <input type="text" name="categories_id[]" value="{{$prioritizedCategoryDetails[$i]->id}}" class="form-control form-control-lg" placeholder="Insert News Id">
                        </div>
                        <div class="col-sm-3">
                            <input type="text" class="form-control form-control-lg" value="{{$prioritizedCategoryDetails[$i]->name}}">
                        </div>
                        <div class="col-sm-3">
                            <input type="text" class="form-control form-control-lg" value="{{$prioritizedCategoryDetails[$i]->name_parent}}">
                        </div>
                    </div>
                    <br>
                    @endfor
                    <div id="appendingPoint"></div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <button type="button" id="addPreference" class="btn btn-success mb-4">Add More Preference</button>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-lg btn-block btn-lg btn-primary">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $("#addPreference").click(function(){
                $("#appendingPoint").append(
                    "<div class=\"row\">\n" +
                    "   <div class=\"col-sm-3\">\n" +
                    "       <button type=\"button\" class=\"btn btn-block btn-warning btn-arrow-right\">Next Preference</button>\n" +
                    "   </div>\n" +
                    "   <div class=\"col-sm-3\">\n" +
                    "       <input type=\"text\" name=\"categories_id[]\" class=\"form-control form-control-lg is-invalid\" placeholder=\"Insert Category Id\">\n" +
                    "   </div>\n" +
                    "   <div class=\"col-sm-3\">\n" +
                    "       <input type=\"text\" class=\"form-control form-control-lg is-valid\" placeholder=\"Leave this empty\">\n" +
                    "   </div>\n" +
                    "   <div class=\"col-sm-3\">\n" +
                    "       <input type=\"text\" class=\"form-control form-control-lg is-valid\" placeholder=\"Leave this empty\">\n" +
                    "   </div>\n" +
                    "</div>\n" +
                    "<br>");
            });
        });
    </script>
@stop